
create extension if not exists pgcrypto;

create table if not exists public.restaurants (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  tagline text,
  description text,
  phone text,
  address text,
  google_maps_url text,
  google_review_url text,
  instagram_url text,
  tiktok_url text,
  cover_image_url text,
  logo_url text,
  currency text not null default 'ETB',
  timezone text not null default 'Africa/Addis_Ababa',
  status text not null default 'active' check (status in ('active','suspended','draft')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.restaurant_members (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('owner','admin','editor','viewer')),
  created_at timestamptz not null default now(),
  unique (restaurant_id, user_id)
);

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  name text not null,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  category_id uuid references public.categories(id) on delete set null,
  name text not null,
  description text,
  price numeric(12,2) not null check (price >= 0),
  image_url text,
  is_available boolean not null default true,
  is_popular boolean not null default false,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.opening_hours (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  weekday int not null check (weekday between 0 and 6),
  opens_at time,
  closes_at time,
  is_closed boolean not null default false,
  unique (restaurant_id, weekday)
);

create table if not exists public.wifi_details (
  restaurant_id uuid primary key references public.restaurants(id) on delete cascade,
  network_name text,
  password_hint text,
  is_visible boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.feedback (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  message text not null check (char_length(message) between 1 and 3000),
  rating int check (rating between 1 and 5),
  status text not null default 'new' check (status in ('new','reviewed','resolved')),
  created_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  event_type text not null check (event_type in ('page_view','menu_view','qr_scan','review_click','directions_click','wifi_click','feedback_open','feedback_submit')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_categories_restaurant on public.categories(restaurant_id, sort_order);
create index if not exists idx_menu_items_restaurant on public.menu_items(restaurant_id, sort_order);
create index if not exists idx_menu_items_category on public.menu_items(category_id);
create index if not exists idx_feedback_restaurant on public.feedback(restaurant_id, created_at desc);
create index if not exists idx_analytics_restaurant on public.analytics_events(restaurant_id, created_at desc);

alter table public.restaurants enable row level security;
alter table public.restaurant_members enable row level security;
alter table public.categories enable row level security;
alter table public.menu_items enable row level security;
alter table public.opening_hours enable row level security;
alter table public.wifi_details enable row level security;
alter table public.feedback enable row level security;
alter table public.analytics_events enable row level security;

create or replace function public.is_restaurant_member(target_restaurant uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.restaurant_members rm
    where rm.restaurant_id = target_restaurant
      and rm.user_id = auth.uid()
  );
$$;

create policy "public read active restaurants"
on public.restaurants for select
using (status = 'active' or public.is_restaurant_member(id));

create policy "members update restaurant"
on public.restaurants for update
using (public.is_restaurant_member(id))
with check (public.is_restaurant_member(id));

create policy "members read memberships"
on public.restaurant_members for select
using (user_id = auth.uid() or public.is_restaurant_member(restaurant_id));

create policy "public read active categories"
on public.categories for select
using (
  exists (
    select 1 from public.restaurants r
    where r.id = restaurant_id and r.status = 'active'
  )
  or public.is_restaurant_member(restaurant_id)
);

create policy "members manage categories"
on public.categories for all
using (public.is_restaurant_member(restaurant_id))
with check (public.is_restaurant_member(restaurant_id));

create policy "public read available menu items"
on public.menu_items for select
using (
  (
    is_available = true
    and exists (
      select 1 from public.restaurants r
      where r.id = restaurant_id and r.status = 'active'
    )
  )
  or public.is_restaurant_member(restaurant_id)
);

create policy "members manage menu items"
on public.menu_items for all
using (public.is_restaurant_member(restaurant_id))
with check (public.is_restaurant_member(restaurant_id));

create policy "public read opening hours"
on public.opening_hours for select
using (
  exists (
    select 1 from public.restaurants r
    where r.id = restaurant_id and r.status = 'active'
  )
  or public.is_restaurant_member(restaurant_id)
);

create policy "members manage opening hours"
on public.opening_hours for all
using (public.is_restaurant_member(restaurant_id))
with check (public.is_restaurant_member(restaurant_id));

create policy "public read visible wifi details"
on public.wifi_details for select
using (
  is_visible = true
  or public.is_restaurant_member(restaurant_id)
);

create policy "members manage wifi details"
on public.wifi_details for all
using (public.is_restaurant_member(restaurant_id))
with check (public.is_restaurant_member(restaurant_id));

create policy "public submit feedback"
on public.feedback for insert
with check (
  exists (
    select 1 from public.restaurants r
    where r.id = restaurant_id and r.status = 'active'
  )
);

create policy "members read feedback"
on public.feedback for select
using (public.is_restaurant_member(restaurant_id));

create policy "members update feedback"
on public.feedback for update
using (public.is_restaurant_member(restaurant_id))
with check (public.is_restaurant_member(restaurant_id));

create policy "public insert analytics"
on public.analytics_events for insert
with check (
  exists (
    select 1 from public.restaurants r
    where r.id = restaurant_id and r.status = 'active'
  )
);

create policy "members read analytics"
on public.analytics_events for select
using (public.is_restaurant_member(restaurant_id));

